version: '3'
services:
  biovalidator:
    image: ebispot/elixir-jsonsschema-validator:1.3.0
    command: npm start
    ports:
      - 3020:3020
#networks:
#  default:
#    ipam:
#      config:
#        - subnet: 172.30.0.0/16